### ISSUE TITLE
Fails to cross-compoile linux to i686-pc-windows-gnu

### ISSUE THREAD

**Issue by robsdedude** [PyO3/maturin#3172]
### Bug Description

Starting with rustc 1.92, I can no longer cross-compile from ubuntu 22.04 to `i686-pc-windows-gnu`.

I get a linker error: 

```
          /usr/bin/i686-w64-mingw32-ld: /root/.rustup/toolchains/1.92-x86_64-unknown-linux-gnu/lib/rustlib/i686-pc-windows-gnu/lib/libstd-5f8529fcda36539e.rlib(std-5f8529fcda36539e.std.4866ca46cbb89ee7-cgu.0.rcgu.o):/rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library\std\src\sys\net\hostname/windows.rs:15: undefined reference to `GetHostNameW@8'
          collect2: error: ld returned 1 exit status
```

Full [build.log](https://github.com/user-attachments/files/27395612/build.log)

Maybe related: 
 * https://blog.rust-lang.org/2025/05/26/demoting-i686-pc-windows-gnu/
 * https://github.com/cross-rs/cross/issues/1754

### Your maturin version (`maturin --version`)

1.13.1

### Your Python version (`python -V`)

3.10.12

### Your pip version (`pip -V`)

26.1.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [x] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. ```bash
   git clone git@github.com:neo4j/neo4j-python-driver-rust-ext.git
   cd neo4j-python-driver-rust-ext
   git checkout 0a006646aa73751ea7d3910e4b165e285d740684
   ````
2. ``docker run --rm -v `pwd`:/driver --workdir /driver -it ubuntu:22.04``
3. Inside docker container:
   ```bash
   apt-get update
   apt-get install -y llvm python3 python3-pip python3-venv python-is-python3 mingw-w64 curl
   curl --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain 1.91
   export PATH="$HOME/.cargo/bin:$PATH"
   rustup target add i686-pc-windows-gnu
   
   rm -rf .venv
   python -m venv .venv
   . .venv/bin/activate
   python -m pip install -U pip
   python -m pip install maturin[zig]

   # works with rustc 1.91
   maturin build --release --interpreter python3.10 --target i686-pc-windows-gnu

   rustup default 1.92 && rustup target add i686-pc-windows-gnu

   # fails with rustc 1.92
   maturin build --release --interpreter python3.10 --target i686-pc-windows-gnu
   ```

**Comment by messense** [comment]
According to https://github.com/cross-rs/cross/pull/1755 you need to use a newer ubuntu docker image.

**Comment by robsdedude** [comment]
I should've seen that 🤦 

Sorry for the noise and thanks for the pointer. Bumping the ubuntu image indeed worked.

Also thanks for maintaining this *fantastic* piece of software ❤️
