### PR TITLE
Normalize python source directory path

### LINKED ISSUE #2290: Function calls in Pyxel fail when using Maturin 1.7.1 or later
### Bug Description

Hi.
I tried compiling Pyxel with Maturin 1.7.1+.

I changed an option in Pyxel's makefile from `--skip-auditwheel` to `--auditwheel` skip and then the compilation finished.
But when run an application, the following error occurs:

```
    pyxel.init(300, 300, title="hoge")
    ^^^^^^^^^^
AttributeError: module 'pyxel' has no attribute 'init'
```

Maturin is called from Pyxel's makefile. https://github.com/kitao/pyxel/blob/main/Makefile#L102

The directory structure of Pyxel may no longer work correctly with Maturin 1.7.1 or later.
https://github.com/kitao/pyxel/blob/main/python/pyproject.toml#L35-L38

https://github.com/kitao/pyxel/issues/574

### Your maturin version (`maturin --version`)

1.7.0 → 1.7.0+

### Your Python version (`python -V`)

Python 3.12.3

### Your pip version (`pip -V`)

pip 24.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

Just build Pyxel and use it.
- Build with `make`
- `pyxel edit` (which calls some Pyxel functions and invoke the error)

### PR DESCRIPTION
**Pull request by messense**
Fixes #2290

### CODE REVIEW

**Comment by messense** [comment]
This change is part of the following stack:

- #2343 ◀

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>
