### ISSUE TITLE
Pyo3 is built with wrong config when building for `3.13t` with `abi3` and `generate-import-lib` both enabled

### ISSUE THREAD

**Issue by kahojyun** [PyO3/maturin#2385]
### Bug Description

When debugging #2368, I notice that if both of `abi3` and `generate-import-lib` are enabled, `maturin build -i 3.13t` doesn't generate `PYO3_CONFIG_FILE` for `pyo3-build-config` to read and `pyo3` will be built with whatever python interpreter it can find from `PATH`.

### Your maturin version (`maturin --version`)

maturin 1.7.8

### Your Python version (`python -V`)

Python 3.12.7

### Your pip version (`pip -V`)

pip 24.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Enable both `abi3` and `generate-import-lib` features
```toml
pyo3 = { version = "0.23.3", features = ["abi3-py39", "generate-import-lib"] }
```
2. Reference `GILProtected` which is not available in free-threaded python `3.13t`
3. Build with `maturin build -i 3.13t` (Python 3.13t not installed so `pyo3` can't find interpreter from `PATH`)
```
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.9
⚠️  Warning: Failed to determine python platform
🐍 Not using a specific python interpreter (automatically generating windows import library)
📡 Using build options features from pyproject.toml
⚠️ Warning: CPython 3.13t does not yet support abi3 so the build artifacts will be version-specific.
   Compiling shlex v1.3.0
   Compiling target-lexicon v0.12.16
   Compiling once_cell v1.20.2
   Compiling proc-macro2 v1.0.92
   Compiling unicode-ident v1.0.14
   Compiling autocfg v1.4.0
   Compiling libc v0.2.168
   Compiling heck v0.5.0
   Compiling indoc v2.0.5
   Compiling unindent v0.2.3
   Compiling cfg-if v1.0.0
   Compiling cc v1.2.4
   Compiling memoffset v0.9.1
   Compiling python3-dll-a v0.2.11
   Compiling quote v1.0.37
   Compiling pyo3-build-config v0.23.3
   Compiling syn v2.0.90
   Compiling pyo3-ffi v0.23.3
   Compiling pyo3-macros-backend v0.23.3
   Compiling pyo3 v0.23.3
   Compiling pyo3-macros v0.23.3
   Compiling wrong-lib v0.1.0 (E:\wrong-lib)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 10.06s
📦 Built wheel for CPython 3.13t to E:\wrong-lib\target\wheels\wrong_lib-0.1.0-cp313-cp313t-win_amd64.whl
```
Expected: compilation error
4. Remove `abi3` feature, compilation fails as expected
```
🔗 Found pyo3 bindings
⚠️  Warning: Failed to determine python platform
🐍 Found CPython 3.13t
📡 Using build options features from pyproject.toml
   Compiling target-lexicon v0.12.16
   Compiling shlex v1.3.0
   Compiling once_cell v1.20.2
   Compiling proc-macro2 v1.0.92
   Compiling unicode-ident v1.0.14
   Compiling autocfg v1.4.0
   Compiling libc v0.2.168
   Compiling heck v0.5.0
   Compiling indoc v2.0.5
   Compiling cfg-if v1.0.0
   Compiling unindent v0.2.3
   Compiling cc v1.2.4
   Compiling memoffset v0.9.1
   Compiling python3-dll-a v0.2.11
   Compiling pyo3-build-config v0.23.3
   Compiling quote v1.0.37
   Compiling syn v2.0.90
   Compiling pyo3-ffi v0.23.3
   Compiling pyo3-macros-backend v0.23.3
   Compiling pyo3 v0.23.3
   Compiling pyo3-macros v0.23.3
   Compiling wrong-lib v0.1.0 (E:\wrong-lib)
error[E0432]: unresolved import `pyo3::sync::GILProtected`
  --> src\lib.rs:1:24
   |
1  | use pyo3::{prelude::*, sync::GILProtected};
   |                        ^^^^^^^^^^^^^^^^^^ no `GILProtected` in `sync`
   |
note: found an item that was configured out
  --> E:\packages\cargo\registry\src\index.crates.io-6f17d22bba15001f\pyo3-0.23.3\src\sync.rs:47:12
   |
47 | pub struct GILProtected<T> {
   |            ^^^^^^^^^^^^
note: the item is gated here
  --> E:\packages\cargo\registry\src\index.crates.io-6f17d22bba15001f\pyo3-0.23.3\src\sync.rs:46:1
   |
46 | #[cfg(not(Py_GIL_DISABLED))]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0432`.
error: could not compile `wrong-lib` (lib) due to 1 previous error
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit code: 101": `"cargo" "rustc" "--features" "pyo3/extension-module" "--message-format" "json-render-diagnostics" "--manifest-path" "E:\\wrong-lib\\Cargo.toml" "--lib"`
```

**Comment by kahojyun** [comment]
It seems that the combination of `abi3`, `generate-import-lib` and non-abi3-compatible version like `3.13t` will confuse `pyo3` and `maturin`. Are users supposed to make these features optional and provide coherent feature combinations in CI?

**Comment by messense** [comment]
Feel free to investigate and send PRs to fix it, I don't have much experience developing on Windows, help appreciated!

**Comment by messense** [comment]
@CastilloDel That was a pyo3 bug, fixed in https://github.com/PyO3/pyo3/pull/4806

**Comment by CastilloDel** [comment]
Perfect! Thanks a lot!
