### ISSUE TITLE
Function calls in Pyxel fail when using Maturin 1.7.1 or later

### ISSUE THREAD

**Issue by kitao** [PyO3/maturin#2290]
### Bug Description

Hi.
I tried compiling Pyxel with Maturin 1.7.1+.

I changed an option in Pyxel's makefile from `--skip-auditwheel` to `--auditwheel` skip and then the compilation finished.
But when run an application, the following error occurs:

```
    pyxel.init(300, 300, title="hoge")
    ^^^^^^^^^^
AttributeError: module 'pyxel' has no attribute 'init'
```

Maturin is called from Pyxel's makefile. https://github.com/kitao/pyxel/blob/main/Makefile#L102

The directory structure of Pyxel may no longer work correctly with Maturin 1.7.1 or later.
https://github.com/kitao/pyxel/blob/main/python/pyproject.toml#L35-L38

https://github.com/kitao/pyxel/issues/574

### Your maturin version (`maturin --version`)

1.7.0 → 1.7.0+

### Your Python version (`python -V`)

Python 3.12.3

### Your pip version (`pip -V`)

pip 24.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

Just build Pyxel and use it.
- Build with `make`
- `pyxel edit` (which calls some Pyxel functions and invoke the error)

**Comment by TomaSajt** [comment]
Bisected my issue in https://github.com/NixOS/nixpkgs/issues/359836 down to the commit added by https://github.com/PyO3/maturin/pull/2158

Not sure if you also encountered this issue, but in our case the issue is that only `pyxel_wrapper.abi3.so` gets installed, none of the non-native stuff does.

(We don't use the makefile, so we didn't encounter the auditwheel stuff)

**Comment by TomaSajt** [comment]
https://github.com/PyO3/maturin/blob/d896c62f31ded33adca2f58819913e29b7950299/src/module_writer.rs#L1329-L1332

After logging out some stuff, it looks like the logic is trying to check if `"/build/source/python/pyxel/cli.py"` starts with `"/build/source/python/../python/pyxel"` but doesn't resolve the `..`, so it skips the file.
This happens with every python file, not just `cli.py`

**Comment by TomaSajt** [comment]
Seems like removing [this line](https://github.com/kitao/pyxel/blob/12e5c43be83a4504876eb2654592f9a56c7d70ba/python/pyproject.toml#L38) from the pyxel repo fixes the issue for that project.

Though, I still think that there are improvements to be made with the prefix stripping logic in the maturin repo.

**Comment by messense** [comment]
@TomaSajt thanks for the investigation!

**Comment by messense** [comment]
IMO we can probably fix it by [`normalize`](https://docs.rs/normpath/latest/normpath/trait.PathExt.html#tymethod.normalize) the `package_path` in https://github.com/PyO3/maturin/blob/d896c62f31ded33adca2f58819913e29b7950299/src/module_writer.rs#L1318

Pull requests are welcome!
