### PR TITLE
Read host target triple from `rustc -vV`

### LINKED ISSUE #478: Strange behavior with PyPy in 0.10 prerelease
Please provide the following information: 
 * Your python version (`python -V`): PyPy 7.3.3 with Python (3.6.12)
 * Your pip version (`pip -V`): 
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version?
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): pyo3
 * Does `cargo build` work? I think so
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:

maturin-0.10.0b6 , https://github.com/milesgranger/pyrus-cramjam/runs/2218894957?check_suite_focus=true errored with

```bash
maturin build -i /opt/hostedtoolcache/PyPy/3.6.12/x64/bin/pypy --release --out dist
🔗 Found pyo3 bindings
🐍 Found PyPy 3.6 at /opt/hostedtoolcache/PyPy/3.6.12/x64/bin/pypy
📦 Built source distribution to dist/cramjam-2.1.0.tar.gz
warning: version requirement `0.6.0+zstd.1.4.8` for dependency `zstd` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
   Compiling cfg-if v1.0.0
   Compiling scopeguard v1.1.0
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed


error: aborting due to previous error


error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed


error: aborting due to previous error


error: could not compile `scopeguard`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --release --target x86_64-unknown-linux-musl --lib --`
```

It's strange that `--target x86_64-unknown-linux-musl` is passed to `cargo rustc`, it works fine with maturin 0.9.4

### PR DESCRIPTION
**Pull request by messense**
Fixes #478, closes #486

cc @al626

### CODE REVIEW

**Comment by konstin** [comment]
I think the best solution for both `maturin build --target xxx --universal2` from #429 and the musl handling from #478 would be reverting #429 and manually failing on the `--target xxx --universal2` case. I.e. I'd prefer #486 and add an extra error path. This also has the advantage that we save a subprocess call.

If there are other reasons I've missing and we still need to go for reading the target triple, I'd do [what cargo does](https://github.com/rust-lang/cargo/blob/1dae5acb7d27568ca30fe2da49b4a447d7b78e90/src/cargo/util/rustc.rs#L50-L68) and read `rustc -vV`:

```rust
use std::process::Command;

use anyhow::{format_err, Context, Result};
use std::str;

fn get_target() -> Result<String> {
    let output = Command::new("rustc")
        .arg("-vV")
        .output()
        .context("Failed to run rustc to get the host target")?;
    let output = str::from_utf8(&output.stdout).context("`rustc -vV` didn't return utf8 output")?;

    let field = "host: ";
    let host = output
        .lines()
        .find(|l| l.starts_with(field))
        .map(|l| &l[field.len()..])
        .ok_or_else(|| {
            format_err!(
                "`rustc -vV` didn't have a line for `{}`, got:\n{}",
                field.trim(),
                output
            )
        })?
        .to_string();
    Ok(host)
}

fn main() -> Result<()> {
    let host = get_target()?;
    println!("target triple: {}", host);
    Ok(())
}
```

**Comment by messense** [comment]
There is also https://github.com/PyO3/maturin/pull/423 affected by target_env

**Comment by messense** [comment]
Anyway I think it's good to get rid of `Platform::guess_current()`.

File: .github/workflows/test.yml [hunk 1]
```diff
@@ -72,6 +75,12 @@ jobs:
         uses: actions-rs/cargo@v1
         with:
           command: test
+      - name: cargo test with musl
+        if: matrix.os == 'ubuntu-latest'
+        uses: actions-rs/cargo@v1
+        with:
+          command: test
+          args: --target x86_64-unknown-linux-musl
```
Comment (konstin) [inline .github/workflows/test.yml:83]: Since we're only shipping musl anyway, wouldn't it make more sense to only run the tests for musl?

**Review by konstin — APPROVED** [review]
Looks good, thank you!

File: .github/workflows/test.yml (hunk 1 above)
Comment (messense) [reply .github/workflows/test.yml:83]: Just in case someone needs to compile maturin from source instead of using prebuilt wheels, for example on some BSD systems?
