### PR TITLE
Fix compiled artifacts being excluded by source path matching

### LINKED ISSUE #2909: Regression in v1.11.0: editable installs don't seem to install .so
### Bug Description

It appears that editable installs don't actually install the .so

### Your maturin version (`maturin --version`)

v1.11.0

### Your Python version (`python -V`)

Python 3.14.2

### Your pip version (`pip -V`)

uv

### What bindings you're using

pyo3

### Does `cargo build` work?

- [x] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [x] Yes

### Steps to Reproduce

```
$ git clone https://github.com/pyca/cryptography
$ cd cryptography
$ uv venv .testtest
$ .testtest/bin/active
$ uv pip install -v '.[test]'
$ find .testtest/lib/python3.14/ -iname "*.dylib"
$ find .testtest/lib/python3.14/ -iname "*.so"
.testtest/lib/python3.14/site-packages/coverage/tracer.cpython-314-darwin.so
.testtest/lib/python3.14/site-packages/_cffi_backend.cpython-314-darwin.so
$ .testtest/bin/python
Python 3.14.2 (main, Dec  5 2025, 16:49:16) [Clang 17.0.0 (clang-1700.4.4.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography import fernet
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    from cryptography import fernet
  File "/Users/alex_gaynor/projects/cryptography/.testtest/lib/python3.14/site-packages/cryptography/fernet.py", line 15, in <module>
    from cryptography.exceptions import InvalidSignature
  File "/Users/alex_gaynor/projects/cryptography/.testtest/lib/python3.14/site-packages/cryptography/exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)
>>> 
```

If you manually edit `pyproject.toml` to pin the `maturin` dependency so 1.10.0 can't be used, this works fine.

### PR DESCRIPTION
**Pull request by messense**
The VirtualWriter introduced in d6d23cf9 checks source paths against exclude patterns, which caused compiled shared libraries to be excluded when projects have patterns like `exclude = ["target/**/*"]` to ignore the Cargo target directory.

Add `add_file_force()` method to VirtualWriter that bypasses exclusion checks, and use it for compiled artifacts and external shared libraries which should always be included in the wheel.

Fixes #2909

### CODE REVIEW

**Comment by messense** [comment]
cc @e-nomem

File: src/binding_generator/mod.rs [hunk 1]
```diff
@@ -175,7 +175,8 @@ where
                     artifact_target.display(),
                     source.display()
                 );
-                writer.add_file(artifact_target, source, true)?;
+                // Use add_file_force to bypass exclusion checks for the compiled artifact
+                writer.add_file_force(artifact_target, source, true)?;
```
Comment (e-nomem) [inline src/binding_generator/mod.rs:179]: We should probably do the same for the additional files a few lines below.

File: src/module_writer/virtual_writer.rs [hunk 2]
```diff
@@ -159,6 +159,27 @@ impl<W: ModuleWriterInternal> VirtualWriter<W> {
...
+    ) -> Result<()> {
+        let target = target.as_ref();
+        let source = source.as_ref();
+        debug!("Adding {} from {}", target.display(), source.display());
+        let source = ArchiveSource::File(FileSourceData {
+            path: source.to_path_buf(),
+            executable,
+        });
+        // Directly insert into tracker, bypassing exclusion checks
+        self.tracker.insert(target.to_path_buf(), source);
```
[the remark this answers is not in the document]
Comment (e-nomem) [reply src/module_writer/virtual_writer.rs]: We probably should still bail out on duplicates. Doesn't need to be this complicated though. Can probably just do `self.tracker.insert(target.to_path_buf(), source).ok_or(anyhow!("add_file_force overwrote an existing tracked file"))?;` or something
