### ISSUE TITLE
Fails to build on LoongArch due to rustix-0.38.30 bump

### ISSUE THREAD

**Issue by ionenwks** [PyO3/maturin#1984]
### Bug Description

Forwarded from the downstream bug report at https://bugs.gentoo.org/926407, see also https://github.com/bytecodealliance/rustix/issues/1009 and https://github.com/bytecodealliance/rustix/commit/8edaecaedc6ca90bdf6e9fc23cb949fbf867bcf4

Just as fyi so that the crate can either be upgraded or downgraded next bump (the libc bump is not in a rustix release as of the writing of this), maturin-1.4.0 still works fine meanwhile.

```
error[E0425]: cannot find value `FS_IOC_SETFLAGS` in module `c`
    --> /var/tmp/portage/dev-util/maturin-1.5.0/work/cargo_home/gentoo/rustix-0.38.30/src/fs/ioctl.rs:161:57
     |
161  |         let ctl = ioctl::Setter::<ioctl::BadOpcode<{ c::FS_IOC_SETFLAGS }>, u32>::new(flags.bits());
     |                                                         ^^^^^^^^^^^^^^^
     |
    ::: /var/tmp/portage/dev-util/maturin-1.5.0/work/cargo_home/gentoo/libc-0.2.152/src/unix/linux_like/linux/mod.rs:2922:1
     |
2922 | pub const SIOCSIFFLAGS: ::c_ulong = 0x00008914;
     | --------------------------------- similarly named constant `SIOCSIFFLAGS` defined here
     |
help: a constant with a similar name exists
     |
161  |         let ctl = ioctl::Setter::<ioctl::BadOpcode<{ c::SIOCSIFFLAGS }>, u32>::new(flags.bits());
     |                                                         ~~~~~~~~~~~~
help: consider importing this constant
     |
5    + use linux_raw_sys::ioctl::FS_IOC_SETFLAGS;
     |
help: if you import `FS_IOC_SETFLAGS`, refer to it directly
     |
161  -         let ctl = ioctl::Setter::<ioctl::BadOpcode<{ c::FS_IOC_SETFLAGS }>, u32>::new(flags.bits());
161  +         let ctl = ioctl::Setter::<ioctl::BadOpcode<{ FS_IOC_SETFLAGS }>, u32>::new(flags.bits());
     |
```

### Your maturin version (`maturin --version`)

1.5.0

### Your Python version (`python -V`)

Python 3.11.8

### Your pip version (`pip -V`)

pip 24.0 from /usr/lib/python3.11/site-packages/pip (python 3.11)

### What bindings you're using

None

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. attempt to build on LoongArch

**Comment by messense** [comment]
Thanks for the report, I guess we should add a simple `cargo check` for this target (and possibly many other non-mainstream targets) on CI to avoid breakage in future releases.

**Comment by messense** [comment]
libc has been upgraded in v1.5.1.
