### ISSUE TITLE
maturin-1.12.6 fails to build on sparc64 linux (1.12.5 is fine)

### ISSUE THREAD

**Issue by ionenwks** [PyO3/maturin#3065]
### Bug Description

I do not have hardware myself but I received a downstream report (https://bugs.gentoo.org/970872) indicating that the reflink-copy crate added in commit 92d919fb may be broken on (at least) sparc64:

```
error[E0425]: cannot find function `ioctl_ficlone` in module `rustix::fs`
  --> /var/tmp/portage/dev-util/maturin-1.12.6/work/maturin-1.12.6/vendor/reflink-copy-0.1.28/src/sys/unix/linux.rs:12:17
   |
12 |     rustix::fs::ioctl_ficlone(&dest, &src)?;
   |                 ^^^^^^^^^^^^^ not found in `rustix::fs`
```

Not familiar with this but from the old pre-fork reflink-copy repo (not the one used for 0.1.28), there was a PR (https://github.com/nicokoch/reflink/pull/7) indicating that ficlone may have portability issues, perhaps still an issue today.

See attachment on the downstream bug if need the full build log + some hardware/toolchain info. rust-1.92.0 was used.

### Your maturin version (`maturin --version`)

1.12.6

### Your Python version (`python -V`)

Python 3.13.12

### Your pip version (`pip -V`)

(unused)

### What bindings you're using

None

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

Build maturin on sparc64 linux.

**Comment by messense** [comment]
Thanks for the report, I've opened an issue in https://github.com/cargo-bins/reflink-copy/issues/163
